---
apiVersion: vi
kind: service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
    author: meg
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    author: meg
    name: postgres-pod
...