---
apiVersion: v1
kind: service
metadata:
  name: redis-service
  labels:
    author: meg
    name: redis-service
spec:
  type: clusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    author: meg
    name: redis-pod
...