---
apiVersion: v1
kind: pod
metadata:
  name: result-app-pod
    labels:
       author: meg
       name: result-app-pod
 spec:
   containers:
     - name: result-app
       image: dockersamples/examplevotingapp_result
       ports:
         - containerPort: 80
...
