---
apiVersion: v1
kind: service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    author: meg
spec:
  type: LoadBalancer
  ports:
    - ports: 80
      targetPort: 80
      nodePort: 8080
  selector:
    author: meg
    name: voting-app-pod
 ---


